services:
  postgres-db:
    image: postgres:15
    container_name: angio_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  orthanc-pacs:
    image: orthancteam/orthanc:latest
    container_name: angio_pacs
    ports:
      - "127.0.0.1:${PORT_ORTHANC_DICOM}:4242"
      - "127.0.0.1:${PORT_ORTHANC_WEB}:8042"
    environment:
      ORTHANC__NAME: ${ORTHANC_NAME}
      ORTHANC__DICOM_AET: ${ORTHANC_AETITLE}
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"
      ORTHANC__AUTHENTICATION_ENABLED: ${ORTHANC_AUTHENTICATION_ENABLED:-false}
      ORTHANC__REGISTERED_USERS: '{"${ORTHANC_BACKEND_USER}":"${ORTHANC_BACKEND_PASSWORD}","${ORTHANC_ADMIN_USER}":"${ORTHANC_ADMIN_PASSWORD}","${ORTHANC_VISIT_USER}":"${ORTHANC_VISIT_PASSWORD}"}'

      # Viewers / APIs
      DICOM_WEB_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC_EXPLORER_2_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"

      # Transfer / workflow
      TRANSFERS_PLUGIN_ENABLED: "true"
      WORKLISTS_PLUGIN_ENABLED: "true"
      ORTHANC__WORKLISTS__DIRECTORY: "/var/lib/orthanc/worklists"
      GDCM_PLUGIN_ENABLED: "true"

      VERBOSE_ENABLED: "true"
    volumes:
      - orthanc_storage:/var/lib/orthanc/db
      - orthanc_worklists:/var/lib/orthanc/worklists
    restart: unless-stopped

  backend-bot:
    build: ./backend
    container_name: angio_backend_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATA_PATH: /app/data
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
      ORTHANC_URL: http://orthanc-pacs:8042
      ORTHANC_PUBLIC_URL: ${ORTHANC_PUBLIC_URL}
      ORTHANC_USER: ${ORTHANC_BACKEND_USER}
      ORTHANC_PASSWORD: ${ORTHANC_BACKEND_PASSWORD}
    volumes:
      - ./fotos_pacientes:/app/data
    ports:
      - "${PORT_BACKEND}:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
      orthanc-pacs:
        condition: service_started

volumes:
  postgres_data:
  orthanc_storage:
  orthanc_worklists:
