#!/usr/bin/env bash

# NeuroPACS / AngioPACS env wizard
# ASCII-safe. Do not add secrets to Git.

set -Eeuo pipefail

APP_NAME="NeuroPACS / AngioPACS"

print_header() {
  echo
  echo "============================================================"
  echo "$1"
  echo "============================================================"
}

is_port_busy() {
  local port="$1"
  ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "(:|\\])${port}$"
}

suggest_free_port() {
  local start="$1"
  local port="$start"

  while is_port_busy "$port"; do
    port=$((port + 1))
  done

  echo "$port"
}

ask_default() {
  local prompt="$1"
  local default="$2"
  local value=""

  read -r -p "${prompt} [${default}]: " value
  if [ -z "$value" ]; then
    value="$default"
  fi

  echo "$value"
}

ask_port() {
  local name="$1"
  local default="$2"
  local suggested="$default"
  local value=""

  if is_port_busy "$default"; then
    suggested="$(suggest_free_port "$default")"
    echo "AVISO: el puerto ${default} para ${name} esta ocupado." >&2
    echo "Sugerencia: ${suggested}" >&2
  fi

  while true; do
    value="$(ask_default "${name}" "${suggested}")"

    if ! [[ "$value" =~ ^[0-9]+$ ]]; then
      echo "ERROR: el puerto debe ser numerico." >&2
      continue
    fi

    if is_port_busy "$value"; then
      echo "AVISO: el puerto ${value} esta ocupado." >&2
      read -r -p "Usarlo de todas formas? [s/N]: " force
      case "$force" in
        s|S|si|SI|Si)
          echo "$value"
          return
          ;;
        *)
          suggested="$(suggest_free_port "$((value + 1))")"
          echo "Nueva sugerencia: ${suggested}" >&2
          ;;
      esac
    else
      echo "$value"
      return
    fi
  done
}

gen_hex() {
  local bytes="${1:-24}"
  python3 - "$bytes" <<'PY'
import secrets
import sys
n = int(sys.argv[1])
print(secrets.token_hex(n))
PY
}

urlencode() {
  python3 - "$1" <<'PY'
from urllib.parse import quote
import sys
print(quote(sys.argv[1], safe=""))
PY
}

write_env() {
  local env_file="$1"

  cat > "$env_file" <<EOF
# ${APP_NAME}
# Generated by scripts/generate_env.sh
# Do not commit this file.

TZ=${TZ_VALUE}

# Web
PORT_BACKEND=${PORT_BACKEND}
WEB_PUBLIC_URL=${WEB_PUBLIC_URL}
ANGIOPACS_PUBLIC_URL=${ANGIOPACS_PUBLIC_URL}

# Initial admin user
ANGIOPACS_BOOTSTRAP_ADMIN=true
ANGIOPACS_USER=${ANGIOPACS_USER}
ANGIOPACS_PASSWORD=${ANGIOPACS_PASSWORD}
ANGIOPACS_SESSION_SECRET=${ANGIOPACS_SESSION_SECRET}

# PostgreSQL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}

# Orthanc
ORTHANC_NAME=${ORTHANC_NAME}
ORTHANC_AETITLE=${ORTHANC_AETITLE}
ORTHANC_BIND_ADDRESS=${ORTHANC_BIND_ADDRESS}
ORTHANC_AUTHENTICATION_ENABLED=${ORTHANC_AUTHENTICATION_ENABLED}

PORT_ORTHANC_WEB=${PORT_ORTHANC_WEB}
PORT_ORTHANC_DICOM=${PORT_ORTHANC_DICOM}

ORTHANC_URL=${ORTHANC_URL}
ORTHANC_PUBLIC_URL=${ORTHANC_PUBLIC_URL}

ORTHANC_BACKEND_USER=${ORTHANC_BACKEND_USER}
ORTHANC_BACKEND_PASSWORD=${ORTHANC_BACKEND_PASSWORD}

ORTHANC_USER=${ORTHANC_BACKEND_USER}
ORTHANC_PASSWORD=${ORTHANC_BACKEND_PASSWORD}

ORTHANC_ADMIN_USER=${ORTHANC_ADMIN_USER}
ORTHANC_ADMIN_PASSWORD=${ORTHANC_ADMIN_PASSWORD}

ORTHANC_VISIT_USER=${ORTHANC_VISIT_USER}
ORTHANC_VISIT_PASSWORD=${ORTHANC_VISIT_PASSWORD}

# Telegram
TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
EOF
}

write_secrets_summary() {
  local secrets_file="$1"

  cat > "$secrets_file" <<EOF
Credentials generated by scripts/generate_env.sh
Do not commit this file.

WEB AngioPACS:
  URL:     ${WEB_PUBLIC_URL}
  Usuario: ${ANGIOPACS_USER}
  Clave:   ${ANGIOPACS_PASSWORD}

Orthanc admin:
  URL:     http://localhost:${PORT_ORTHANC_WEB}
  Usuario: ${ORTHANC_ADMIN_USER}
  Clave:   ${ORTHANC_ADMIN_PASSWORD}

Orthanc backend:
  Usuario: ${ORTHANC_BACKEND_USER}
  Clave:   ${ORTHANC_BACKEND_PASSWORD}

PostgreSQL:
  Usuario: ${POSTGRES_USER}
  Base:    ${POSTGRES_DB}
  Clave:   ${POSTGRES_PASSWORD}

Variables principales:
PORT_BACKEND=${PORT_BACKEND}
PORT_ORTHANC_WEB=${PORT_ORTHANC_WEB}
PORT_ORTHANC_DICOM=${PORT_ORTHANC_DICOM}
ORTHANC_PUBLIC_URL=${ORTHANC_PUBLIC_URL}
ORTHANC_AUTHENTICATION_ENABLED=${ORTHANC_AUTHENTICATION_ENABLED}
ORTHANC_BIND_ADDRESS=${ORTHANC_BIND_ADDRESS}
WEB_PUBLIC_URL=${WEB_PUBLIC_URL}
ANGIOPACS_PUBLIC_URL=${ANGIOPACS_PUBLIC_URL}
EOF
}

print_header "$APP_NAME env wizard"

echo "This wizard creates a local .env file."
echo "It checks if common ports are already busy."
echo "It creates a backup if .env already exists."
echo

print_header "Port configuration"

PORT_BACKEND="$(ask_port "PORT_BACKEND" "8000")"
PORT_ORTHANC_WEB="$(ask_port "PORT_ORTHANC_WEB" "8042")"
PORT_ORTHANC_DICOM="$(ask_port "PORT_ORTHANC_DICOM" "4242")"

print_header "Public URLs"

DEFAULT_WEB_URL="http://localhost:${PORT_BACKEND}"
WEB_PUBLIC_URL="$(ask_default "WEB_PUBLIC_URL" "$DEFAULT_WEB_URL")"
ANGIOPACS_PUBLIC_URL="$(ask_default "ANGIOPACS_PUBLIC_URL" "$WEB_PUBLIC_URL")"

echo
echo "ORTHANC_PUBLIC_URL should usually be /orthanc."
echo "This avoids asking users for the Orthanc password in the browser."
ORTHANC_PUBLIC_URL="$(ask_default "ORTHANC_PUBLIC_URL" "/orthanc")"

print_header "Orthanc internal configuration"

ORTHANC_URL="$(ask_default "ORTHANC_URL" "http://orthanc-pacs:8042")"
ORTHANC_NAME="$(ask_default "ORTHANC_NAME" "NeuroPACS")"
ORTHANC_AETITLE="$(ask_default "ORTHANC_AETITLE" "ORTHANC")"
ORTHANC_BIND_ADDRESS="$(ask_default "ORTHANC_BIND_ADDRESS" "127.0.0.1")"
ORTHANC_AUTHENTICATION_ENABLED="$(ask_default "ORTHANC_AUTHENTICATION_ENABLED" "true")"

print_header "Database configuration"

POSTGRES_USER="$(ask_default "POSTGRES_USER" "admin_angio")"
POSTGRES_DB="$(ask_default "POSTGRES_DB" "angiopacs_db")"

print_header "Application user"

ANGIOPACS_USER="$(ask_default "ANGIOPACS_USER" "admin")"

print_header "Telegram"

TELEGRAM_TOKEN="$(ask_default "TELEGRAM_TOKEN" "CAMBIAR_TELEGRAM_TOKEN")"

print_header "Generate secrets"

ANGIOPACS_PASSWORD="$(gen_hex 16)"
ANGIOPACS_SESSION_SECRET="$(gen_hex 32)"

POSTGRES_PASSWORD="$(gen_hex 24)"

ORTHANC_BACKEND_USER="angio_backend"
ORTHANC_BACKEND_PASSWORD="$(gen_hex 24)"

ORTHANC_ADMIN_USER="admin_orthanc"
ORTHANC_ADMIN_PASSWORD="$(gen_hex 24)"

ORTHANC_VISIT_USER="visita"
ORTHANC_VISIT_PASSWORD="$(gen_hex 24)"

TZ_VALUE="$(ask_default "TZ" "America/Santiago")"

ENC_POSTGRES_USER="$(urlencode "$POSTGRES_USER")"
ENC_POSTGRES_PASSWORD="$(urlencode "$POSTGRES_PASSWORD")"
ENC_POSTGRES_DB="$(urlencode "$POSTGRES_DB")"

DATABASE_URL="postgresql://${ENC_POSTGRES_USER}:${ENC_POSTGRES_PASSWORD}@postgres-db:5432/${ENC_POSTGRES_DB}"

print_header "Consistency checks"

if [ "$ORTHANC_PUBLIC_URL" != "/orthanc" ]; then
  echo "AVISO: ORTHANC_PUBLIC_URL no es /orthanc."
  echo "Valor actual: ${ORTHANC_PUBLIC_URL}"
  echo "Esto puede hacer que el navegador vaya directo a Orthanc y pida clave."
fi

if [ "$ORTHANC_AUTHENTICATION_ENABLED" != "true" ]; then
  echo "AVISO: ORTHANC_AUTHENTICATION_ENABLED no es true."
  echo "En produccion se recomienda true."
fi

if [ "$ORTHANC_BIND_ADDRESS" != "127.0.0.1" ]; then
  echo "AVISO: ORTHANC_BIND_ADDRESS no es 127.0.0.1."
  echo "Revise si Orthanc quedara expuesto fuera del host."
fi

print_header "Write files"

if [ -f .env ]; then
  TS="$(date +%Y%m%d_%H%M%S)"
  cp .env ".env.bak.${TS}"
  echo "Backup created: .env.bak.${TS}"
fi

write_env ".env"
write_secrets_summary ".env.generated.secrets.txt"

chmod 600 .env .env.generated.secrets.txt

echo "OK: .env generated"
echo "OK: .env.generated.secrets.txt generated"
echo

print_header "Summary"

cat .env.generated.secrets.txt

echo
echo "Next steps:"
echo "  docker compose up -d --build"
echo "  docker compose ps"
echo "  Open: ${WEB_PUBLIC_URL}/login"
